title:  Mau
author: MauMagnaguagno
url:    https://maumagnaguagno.github.io

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: css
  style:    compressed

permalink: /:title

exclude: README.md

gems: jemoji

safe: true
lsi: false