title:  Mau
author: MauMagnaguagno
url:    https://maumagnaguagno.github.io

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

sass:
  sass_dir: css
  style:    compressed

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false