url: https://maumagnaguagno.github.io
title: Mau
author: MauMagnaguagno
keywords: Crazy,PDDL,Ruby,MauMagnaguagno
description: Random thoughts of a deterministic mind.

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: css
  style: compressed

jemoji:
  align: nil

permalink: /:title

exclude: README.md

gems: jemoji

safe: true
lsi: false