title:   'Mau'
author:
  name:  'MauMagnaguagno'

path: .
url:  'http://maumagnaguagno.github.io'

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: css
  style:    expanded

categories: [fruit, meat, vegetable, cheese, drink]

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false