title:  Mau
author: MauMagnaguagno
url:    https://maumagnaguagno.github.io

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

sass:
  sass_dir: css
  style:    compressed

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false