title: Mau
author: MauMagnaguagno
keywords: Crazy,PDDL,Ruby,MauMagnaguagno
description: Random thoughts of a deterministic mind.

sass:
  sass_dir: css
  style: compressed

permalink: /:title

exclude: README.md