title:   'Mau'
author:
  name:  'MauMagnaguagno'

path: /docs
url:  'http://maumagnaguagno.github.io'

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false