title: Mau
description: Random thoughts of a deterministic mind.

sass:
  sass_dir: css
  style: compressed

permalink: /:title

collections:
  test:
    output: true
    permalink: /test/:title

exclude: README.md